### ISSUE TITLE
Env variables in Procfile are causing errors

### ISSUE THREAD

**Issue by luislavena** [flynn-archive/slugrunner#1]
Given a simple sinatra app with a base `Procfile`:

```
web: bundle exec app.rb -p $PORT
```

And executed with:

```
$ cat example-ruby-sinatra-v1.tgz | docker run -e PORT=5000 -p 5000:5000 -i -a stdin -a stdout -a stderr flynn/slugrunner start web
```

The env variables are not properly translated from the execution line, resulting in error:

```
/app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.2/lib/sinatra/main.rb:16:in `Integer': invalid value for Integer(): "$PORT" (ArgumentError)
```

However the variable is properly assigned:

```
$ cat example-ruby-sinatra-v1.tgz | docker run -e PORT=5000 -p 5000:5000 -i -a stdin -a stdout -a stderr flynn/slugrunner ruby -ve "p ENV['PORT']"
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux]
"5000"
```

Thank you.

**Comment by progrium** [comment]
Great catch, I was just about it test that too. Looking into it.

On Sunday, October 20, 2013, Luis Lavena wrote:

> Given a simple sinatra app with a base Procfile:
> 
> web: bundle exec app.rb -p $PORT
> 
> And executed with:
> 
> $ cat example-ruby-sinatra-v1.tgz | docker run -e PORT=5000 -p 5000:5000 -i -a stdin -a stdout -a stderr flynn/slugrunner start web
> 
> The env variables are not properly translated from the execution line,
> resulting in error:
> 
> /app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.2/lib/sinatra/main.rb:16:in `Integer': invalid value for Integer(): "$PORT" (ArgumentError)
> 
> However the variable is properly assigned:
> 
> $ cat example-ruby-sinatra-v1.tgz | docker run -e PORT=5000 -p 5000:5000 -i -a stdin -a stdout -a stderr flynn/slugrunner ruby -ve "p ENV['PORT']"
> ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux]
> "5000"
> 
> Thank you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/issues/1
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
Should be resolve in latest. You want to double check?

**Comment by luislavena** [comment]
@progrium works perfectly, thank you! :heart: :heart: :heart: 

```
$ cat example-ruby-sinatra-v1.tgz | docker run -e PORT=5000 -p 5000:5000 -i -a stdin -a stdout -a stderr flynn/slugrunner start web
[2013-10-21 13:20:27] INFO  WEBrick 1.3.1
[2013-10-21 13:20:27] INFO  ruby 1.9.3 (2013-06-27) [x86_64-linux]
== Sinatra/1.4.2 has taken the stage on 5000 for production with backup from WEBrick
[2013-10-21 13:20:27] INFO  WEBrick::HTTPServer#start: pid=25 port=5000
172.17.42.1 - - [21/Oct/2013 13:20:52] "GET / HTTP/1.1" 200 16 0.0020
172.17.42.1 - - [21/Oct/2013:13:20:52 UTC] "GET / HTTP/1.1" 200 16
- -> /
```
