### ISSUE TITLE
docker start/stop not supported

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/slugrunner#6]
If a container is stopped, and than started, it will appear to run but do nothing, since it hangs on the initial "cat" waiting for stdin. This is, at the very least, highly confusing.

I wonder if it might have been fixed via #5.

**Comment by progrium** [comment]
Hmm. It wasn't designed to support containers that are stopped and then
started again. I believe #5 would help in that situation.

On Mon, Dec 30, 2013 at 8:06 PM, Michael Elsdörfer <notifications@github.com

> wrote:
> 
> If a container is stopped, and than started, it will appear to run but do
> nothing, since it hangs on the initial "cat" waiting for stdin. This is, at
> the very least, highly confusing.
> 
> I wonder if it might have been fixed via #5https://github.com/flynn/slugrunner/pull/5
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/issues/6
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by miracle2k** [comment]
Admittedly, I'm still trying to figure the whole docker thing out (e.g. how best to restore containers after a reboot, it doesn't seem well documented) - maybe stop/start is not the way to go. But an error message would have saved me some time. 

Of course, if #5 indeed fixes the issue, even better.

**Comment by titanous** [comment]
Closing, since no other Flynn components support stop/start either.

**Comment by miracle2k** [comment]
For reference though, with #5 start/stop works fine currently.
